BotInfo:
  token: 'Put your token here'
  ownerId: 'Put your discord id here'
  guildId: 'Put your server id here'
BotStatus:
  status: 'DND' #Avaiable statuses: DND, ONLINE, IDLE, INVISIBLE
  enableActivity: true
  activity: 'PLAYING' #Avaiable activities: PLAYING, WATCHING, LISTENING, STREAMING
  activityName: 'Raveolution'
Logs:
  logsChannelId: '934518991328784424'
XPSystem:
  enabled: true
  delay: '5m'  #Delay between xp gain, (s, m, h, d)
  lvlUpMsg: true  #If set to false, bot will not respond if someone levelup
  lvlUpMsgStr: 'Well played %user%, you just advanced to level %level%'
Advertising:
  allow: false #if set to false, this will block all discord invite links that are not pointing to your server
  dmAdvertiser: true #if set to true, it will send dm to user who tried to advertise, if false it will send message in channel
  message: 'Hey, %user%, advertising is not allowed here!'
Embeds:
  leaderboards:
    title: 'Raveolution ranking'
    thumbnailUrl: "https://cdn.discordapp.com/avatars/913832514005643314/df612a912243f84fcce186ff1d3fbf2f.png" #you can leave this empty for no thumbnail
Clear:
  messageSuccess: 'Successfully removed %number% messages :thumbsup:' #%number% is a placeholder
  allowedRanks:
    - '943129068499509358' #you can add more by just adding to list